---
- name: Remove file motd
  ansible.builtin.file:
    path: /etc/motd
    state: absent

- name: Ensure login warning banner is configured properly
  template:
    src: "etc/issue.j2"
    dest: "/etc/{{ item }}"
    backup: yes
  with_items:
    - issue
    - issue.net

- name: Ensure permissions on /etc/issue and /etc/issue.net are configured
  ansible.builtin.file:
    path: /etc/{{item}}
    owner: root
    group: root
    mode: 'u-x,go-wx'
  with_items:
    - issue
    - issue.net


