---
- name: Remove deprecated or insecure packages | package-01 - package-09
  ansible.builtin.yum:
    name: "{{ yum_os_security_packages_list }}"
    state: absent
  when: yum_os_security_packages_clean | bool

- name: Run the equivalent of "yum update"
  ansible.builtin.yum:
    update_cache: true

- name: Disable the rhnsd Daemon
  ansible.builtin.systemd:
    name: rhnsd
    masked: true