---
# tasks file for ansible/roles/apache
- name: install apache2
  package: 
    name: apache2 
    state: present
  when: ansible_os_family == "Debian"

- name: install httpd
  package: 
    name: httpd 
    state: present
  when: ansible_os_family == "RedHat"

# - name: install apache solaris
#   package: 
#     name: apache 
#     state: present
#   when: ansible_os_family == "Solaris"


