---
- name: Update package cache
  yum:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade nginx packages to their latest version
  yum:
    name: "{{ web_server }}={{ web_server_version }}"
    state: present

- name: Start Apache HTTP Server
  service:
    name: "{{ web_server }}"
    state: started



