---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Uninstall package on Ubuntu
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ package_name.split(',') }}"

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
    