- name: Run "apt-get update"
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - curl
    - git
    - htop
    - locales
    - software-properties-common
    - sudo
    - unzip
    - vim
    - wget
    - zip
    - net-tools

- name: Update locales
  locale_gen:
    name: en_US.UTF-8
    state: present
