---
######### To Depaly all users in home directory ###############
# - name: To list all users in home directory 
#   shell: 
#     "ls -l /export/home/"
#   register: user_home_dir
# - name: create file check home user
#   copy:
#     content: |
#           ========== List all User Home Directory ( {{OS}} ) ==========
#           Server Name: {{ ansible_hostname }}
#           IP: {{ ansible_default_ipv4['address'] }} 
#           OS: {{ ansible_distribution }}

#           {{ user_home_dir.stdout }}
#           ===========
#     dest: "./list_user_home.txt"
######### To Depaly all users in home directory ###############

######### To Deplay User Create Date and Modified Date #########
- name: To list all users home directory with Modify, Change, Birth and Access
  shell: 
    stat /export/home/*
  register: user_home_dir 
- name: create file check home user
  copy:
    content: |
          ========== List all User Home Directory ( {{OS}} ) ==========
          Server Name: {{ ansible_hostname }}
          IP: {{ ansible_default_ipv4['address'] }} 
          OS: {{ ansible_distribution }}

          {{ user_home_dir.stdout }}

          ======================================================

    dest: "./list_user_home.txt"
######### To Deplay User last login with last 5 times ##########
- name: Store file into /tmp/list_user_home/
  ansible.builtin.fetch:
    src: ./list_user_home.txt
    dest: /tmp/list_user_home/

- name: Remove list_user_home.txt file
  ansible.builtin.file:
    path: './list_user_home.txt'
    state: absent