---
########## This Playbook use for copy original configuration ########
- name: Check that the file resolv.conf exists
  stat:
    path: /etc/resolv.conf.orig
  register: stat_result
- name: backup default DNS configuratioin file
  command: cp /etc/resolv.conf /etc/resolv.conf.orig
  when: not stat_result.stat.exists

- name: Check that the file password-auth exists
  stat:
    path: /etc/pam.d/password-auth.orig
  register: stat_result
- name: backup default config file password-auth
  command: cp /etc/pam.d/password-auth /etc/pam.d/password-auth.orig
  when: not stat_result.stat.exists
- name: Check that the file system-auth  exists
  stat:
    path: /etc/pam.d/system-auth.orig
  register: stat_result
- name: backup default config file system-auth
  command: cp /etc/pam.d/system-auth /etc/pam.d/system-auth.orig
  when: not stat_result.stat.exists

- name: Check that the file /etc/login.defs exists
  stat:
    path: /etc/login.defs.orig
  register: stat_result
- name: backup default config file system-auth
  command: cp -R /etc/login.defs /etc/login.defs.orig
  when: not stat_result.stat.exists

- name: Check that the file pwquality.conf exists
  stat:
    path: /etc/security/pwquality.conf.orig
  register: stat_result
- name: backup default config file pwquality.conf
  command: cp /etc/security/pwquality.conf /etc/security/pwquality.conf.orig
  when: not stat_result.stat.exists

- name: Check that the file bashrc.orig exists
  stat:
    path: /etc/bashrc.orig
  register: stat_result
- name: backup default config file bashrc
  command: cp -R /etc/bashrc /etc/bashrc.orig
  when: not stat_result.stat.exists

- name: Check that the file profile.orig exists
  stat:
    path: /etc/profile.orig
  register: stat_result
- name: backup default config file profile
  command: cp -R /etc/profile /etc/profile.orig
  when: not stat_result.stat.exists

- name: Check that the file ssh_config.orig exists
  stat:
    path: /etc/ssh_config.orig
  register: stat_result
- name: backup default config file ssh_config
  command: cp /etc/ssh/ssh_config  /etc/ssh_config.orig
  when: not stat_result.stat.exists

- name: Check that the file sshd_config.orig exists
  stat:
    path: /etc/ssh/sshd_config.orig
  register: stat_result
- name: backup default config file sshd_config
  command: cp /etc/ssh/sshd_config /etc/ssh/sshd_config.orig
  when: not stat_result.stat.exists

- name: Check that the file pam.d.orig exists
  stat:
    path: /etc/pam.d.orig
  register: stat_result
- name: backup default config file pam.d
  command: cp -R /etc/pam.d /etc/pam.d.orig
  when: not stat_result.stat.exists

- name: Check that the file pam.d/sshd.orig exists
  stat:
    path: /etc/pam.d/sshd.orig
  register: stat_result
- name: backup default config file pam.d/sshd
  command: cp /etc/pam.d/sshd /etc/pam.d/sshd.orig
  when: not stat_result.stat.exists

- name: Check that the file ssh.orig exists
  stat:
    path: /etc/ssh.orig
  register: stat_result
- name: backup default config file ssh.orig
  command: cp -R /etc/ssh /etc/ssh.orig
  when: not stat_result.stat.exists

- name: Check that the file modprobe.d.orig exists
  stat:
    path: /etc/modprobe.d.orig
  register: stat_result
- name: backup default config file modprobe.d
  command: cp -R /etc/modprobe.d /etc/modprobe.d.orig
  when: not stat_result.stat.exists

- name: Check that the file issue.orig exists
  stat:
    path: /etc/issue.orig
  register: stat_result
- name: backup default config file issue
  command: cp -R /etc/issue /etc/issue.orig
  when: not stat_result.stat.exists

- name: Check that the file issue.net.orig exists
  stat:
    path: /etc/issue.net.orig
  register: stat_result
- name: backup default config file issue.net
  command: cp /etc/issue.net /etc/issue.net.orig
  when: not stat_result.stat.exists

- name: Check that the file sysctl.d.orig exists
  stat:
    path: /etc/sysctl.d.orig
  register: stat_result
- name: backup default config file sysctl.d
  command: cp -R /etc/sysctl.d /etc/sysctl.d.orig
  when: not stat_result.stat.exists

- name: Check that the file sysctl.conf.orig exists
  stat:
    path: /etc/sysctl.conf.orig
  register: stat_result
- name: backup default config file sysctl.conf
  command: cp /etc/sysctl.conf /etc/sysctl.conf.orig
  when: not stat_result.stat.exists

- name: Check that the file rsyslog.conf.orig exists
  stat:
    path: /etc/rsyslog.conf.orig
  register: stat_result
- name: backup default config file rsyslog.conf
  command: cp /etc/rsyslog.conf /etc/rsyslog.conf.orig
  when: not stat_result.stat.exists
  ignore_errors: true
- name: Check that the file rsyslog.d.orig exists
  stat:
    path: /etc/rsyslog.d.orig
  register: stat_result
- name: backup default config file rsyslog.d
  command: cp -R /etc/rsyslog.d /etc/rsyslog.d.orig
  when: not stat_result.stat.exists

- name: Check that the file sudoer.orig exists
  stat:
    path: /etc/sudoer.orig
  register: stat_result
- name: backup default config file sudoer
  command: cp -R /etc/sudoers /etc/sudoer.orig
  when: not stat_result.stat.exists

- name: Check that the file sudoers.d.orig exists
  stat:
    path: /etc/sudoers.d.orig
  register: stat_result
- name: backup default config file sudoers.d
  command: cp -R /etc/sudoers.d /etc/sudoers.d.orig
  when: not stat_result.stat.exists

- name: Check that the file security.orig exists
  stat:
    path: /etc/security.orig
  register: stat_result
- name: backup default config file security
  command: cp -R /etc/security /etc/security.orig
  when: not stat_result.stat.exists

- name: Check that the file group.orig exists
  stat:
    path: /etc/group.orig
  register: stat_result
- name: backup default config file group
  command: cp -R /etc/group /etc/group.orig
  when: not stat_result.stat.exists

- name: Check that the file shadow.orig exists
  stat:
    path: /etc/shadow.orig
  register: stat_result
- name: backup default config file shadow
  command: cp -R /etc/shadow /etc/shadow.orig
  when: not stat_result.stat.exists

- name: Check that the file gshadow.orig exists
  stat:
    path: /etc/gshadow.orig
  register: stat_result
- name: backup default config file gshadow
  command: cp -R /etc/gshadow /etc/gshadow.orig
  when: not stat_result.stat.exists

- name: Check that the file fstab.orig exists
  stat:
    path: /etc/fstab.orig
  register: stat_result
- name: backup default config file fstab
  command: cp -R /etc/fstab /etc/fstab.orig
  when: not stat_result.stat.exists

- name: Check that the file faillock.conf.orig exists
  stat:
    path: /etc/security/faillock.conf.orig
  register: stat_result
- name: backup default config file faillock
  command: cp /etc/security/faillock.conf /etc/security/faillock.conf.orig
  when: not stat_result.stat.exists
  ignore_errors: true
