---
- name: to install the pam_pwquality module | Ignore if no Internet
  shell:
      "apt install libpam-pwquality -y"

- name: Insert tasks to setting pwquality ubunut18
  ansible.builtin.template:
    src: ../../os_hardening/templates/etc/security/pwquality_ubuntu.j2
    dest: /etc/security/pwquality.conf
    owner: root
    group: root
    mode: "0640"
  ignore_errors: true
- name: Insert tasks to pam.d common-account ubuntu18
  ansible.builtin.template:
    src: ../../os_hardening/templates/etc/pam.d/ubuntu18/common-account.j2
    dest: /etc/pam.d/common-account
    owner: root
    group: root
    mode: "0640"
  ignore_errors: true
- name: Insert tasks to pam.d common-auth ubuntu18
  ansible.builtin.template:
    src: ../../os_hardening/templates/etc/pam.d/ubuntu18/common-auth.j2
    dest: /etc/pam.d/common-auth
    owner: root
    group: root
    mode: "0640"
  ignore_errors: true
- name: Insert tasks to pam.d common-password ubuntu18.04
  ansible.builtin.template:
    src: ../../os_hardening/templates/etc/pam.d/ubuntu18/common-password.j2
    dest: /etc/pam.d/common-password
    owner: root
    group: root
    mode: "0640"
  ignore_errors: true
# - name: resart service  pam-auth-update
#   command: sudo pam-auth-update --force --package
#   ignore_errors: true
#### Login.defs ###   
# - name: Insert tasks to ubuntu-login.defs
#   ansible.builtin.template:
#     src: ../../os_hardening/templates/etc/ubuntu-login.defs.j2
#     dest: /etc/login.defs
#     owner: root
#     group: root
#     mode: "0640"
 
- name: Set PASS_MAX_DAYS 90 Ubuntu
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^(.*)PASS_MAX_DAYS(.*)$' 
    line: 'PASS_MAX_DAYS 90'
    backrefs: yes
- name: Set PASS_MIN_DAYS 1 Ubuntu
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^(.*)PASS_MIN_DAYS(.*)$' 
    line: 'PASS_MIN_DAYS 1'
    backrefs: yes
- name: Set PASS_WARN_AGE 7 Ubuntu
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^(.*)PASS_WARN_AGE(.*)$' 
    line: 'PASS_WARN_AGE 14'
    backrefs: yes
- name: Set LOGIN_RETRIES 5 Ubuntu
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^(.*)LOGIN_RETRIES(.*)$' 
    line: 'LOGIN_RETRIES           5'
    backrefs: yes
- name: Set LOGIN_TIMEOUT 1800 Ubuntu
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^(.*)LOGIN_TIMEOUT(.*)$' 
    line: 'LOGIN_TIMEOUT           1800'
    backrefs: yes
# - name: Set ENCRYPT_METHOD yescrypt Ubuntu
#   ansible.builtin.lineinfile:
#     path: /etc/login.defs
#     regexp: '^(.*)ENCRYPT_METHOD(.*)$' 
#     line: 'ENCRYPT_METHOD yescrypt'
#     backrefs: yes
    
#### Login.defs ###  
- name: Ensure lockout for failed password attempts is configured deny = 5
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    regexp: '^(.*)deny =(.*)$' 
    line: 'deny = 5'
    backrefs: yes
  ignore_errors: true
- name: Ensure lockout for failed password attempts is configured fail_interval = 900
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    regexp: '^(.*)fail_interval =(.*)$' 
    line: 'fail_interval = 900'
    backrefs: yes
  ignore_errors: true
- name: Ensure lockout for failed password attempts is configured unlock_time = 1800
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    regexp: '^(.*)unlock_time =(.*)$' 
    line: 'unlock_time = 1800'
    backrefs: yes
  ignore_errors: true
- name: Ensure inactive password lock is 90 days for New User account
  command: useradd -D -f 90
# - name: Ensure inactive password lock is 90 days for specific User account
#   command: chage --inactive 90 amkuser1
#   ignore_errors: true
# - name: manual apply password age to specific user
#   command: chage --mindays 7  --maxdays 90 --warndays 14 amkuser1
#   ignore_errors: true
- name: Insert tasks to setting sshd_config Ubuntu
  ansible.builtin.template:
    src: ../../os_hardening/templates/etc/ssh/debian/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0640"
- name: Ensure default user shell timeout is 900 seconds or less
  ansible.builtin.blockinfile:
    path: /etc/profile.d/01-locale-fix.sh
    block: |
      TMOUT=900 readonly TMOUT export TMOUT
  ignore_errors: true

# - name: To solve the problme can't change password or password unchanged
#   command: pam-auth-update --force --package
#   ignore_errors: true


#Below is the task to apply pw polict spcific user
# - name: manual apply password age to specific user
#   command: chage --mindays 7  --maxdays 90 --warndays 14 amkpgf
#   ignore_errors: true