- name: install python3 ubuntu
  raw: test -e /usr/bin/python3 || (apt-get -y update && apt install -y python3 && apt install -y python3-pip )
  register: output
  changed_when: output.stdout
  tags:
    - skip_ansible_lint
  when: ansible_os_family == "Debian"
  ignore_errors: true
  
# - name: install python3 redhat
#   raw: test -e /usr/bin/python3 || (yum -y update && yum install -y python3 && yum install -y python3-pip )
#   register: output
#   changed_when: output.stdout
#   tags:
#     - skip_ansible_lint
#   when: ansible_os_family == "RedHat"

  #### Solaris Not yet #####
- name: Collect facts
  setup:
