- name: Check if users exist
  ansible.builtin.user:
    name: "{{ user }}"
  check_mode: true
  register: users_result
- debug: 
    msg: "{{ users_result }}"
- name: Update Password User {{ user }}
  ansible.builtin.user:
    name: "{{ user }}"
    update_password: always
    password: "{{ password | password_hash('sha512') }}"
  when: false in users_result.values()