- name: checkout to main branch
  command: "{{item}}"
  args: 
    chdir: "{{workspace}}/"
  loop: 
    - git checkout main
    - git pull
- name: add host user operation (solaris)
  ansible.builtin.lineinfile:
    path: "{{workspace}}/ansible/inventory/{{ENV}}/user-operation-hosts"
    insertafter: EOF
    line: "{{server_name}}-{{ENV}} ansible_ssh_host={{ server_ip }} ansible_ssh_user=amkdevops"
    state: present
- name: add host for hardening server (solaris)
  ansible.builtin.lineinfile:
    path: "{{workspace}}/ansible/inventory/{{ENV}}/{{OS}}/hardening-server-hosts"
    regexp: '^[solaris] '
    insertafter: '^\[solaris\]'
    line: "{{server_name}}-{{ENV}} ansible_ssh_host={{ server_ip }} ansible_ssh_user=amkdevops"
    state: present
- name: add host for patching server (solaris)
  ansible.builtin.lineinfile:
    path: "{{workspace}}/ansible/inventory/{{ENV}}/{{OS}}/patching-server-hosts"
    regexp: '^[solaris] '
    insertafter: '^\[solaris\]'
    line: "{{server_name}}-{{ENV}} ansible_ssh_host={{ server_ip }} ansible_ssh_user=amkdevops"
    state: present
- name: git status
  command: git status
  args:
    chdir: "{{workspace}}/"
  register: status
- name: add new host to gitlab
  command: git add {{item}}
  args: 
    chdir: "{{workspace}}/"
  loop: 
    - "{{workspace}}/ansible/inventory/{{ENV}}/user-operation-hosts"
    - "{{workspace}}/ansible/inventory/{{ENV}}/{{OS}}/hardening-server-hosts"
    - "{{workspace}}/ansible/inventory/{{ENV}}/{{OS}}/patching-server-hosts"
  when: '"modified" in status.stdout'
- name: commit and push
  command: "{{item}}"
  args: 
    chdir: "{{workspace}}/"
  loop: 
    - git commit -m "add new host server"
    - git push origin main
  when: '"modified" in status.stdout'